### ISSUE TITLE
some build instructions?

### ISSUE THREAD

**Issue by alexzapatka** [MediatekAndroidDevelopers/android_device_jiayu_s3_h560#1]
i know you guys are busy... and i know mediatek is a heck of a lot different in the build process then a standard rom, but do you think you could post some build instructions?  just some basics?

here is the thing... if i follow the standard CM or AICP build instructions, usually there is a whole process of initializing a git repo based on a manifest file.  with all the sources you provide, there are no manifest files.  

also, with CM13 (and others) usually the kernel source is part of the ROM source, where as you guys have it in two separate git trees.  

i mean, i can use git and clone one of the branches... but is it complete?  it looks like i need to still extract the binary blobs from the current builds (which is fine, but still)...

i don't need you guys to spell it all out for us.  but a basic:  this is what you need to do to get going.  

anyway, thanks for doing all of this!

**Comment by dragonpt** [comment]
Build instructions are the same as of in any other ROM
You repo sync ROM source, and use the proper device & vendor 

As for kernel,  -right now- kernel is not being built inline (within cm/aicp/AOSPA, whatever) we build the kernel independently and then use the -then- pre built within the device 
(Check device, you'll see a prebuilt kernel  blob)

As for the other repos that needed proper modifications -MediaTek wise-  (I.e.: frameworks_av) we cannot yet push those modifications due to the small pieces &bites of MediaTek proprietary source )
As of now , we where abled to work around proprietary MediaTek source on many sub-repos by using our own implementation (s) and also by using AOSP/GPL based source.
But there's still the need of using some bites&bytes of proprietary source that unfortunately cannot be yet be shared due to MediaTek own policies.

Cheers

**Comment by alexzapatka** [comment]
so, adding something like this to the default.xml manifest should get the build started for s3
`

  <project path="device/jiayu/h560"      name="MediatekAndroidDevelopers/android_device_jiayu_s3_h560"  revision="cm-13.0"/>
  <project path="vendor/jiayu/h560"      name="MediatekAndroidDevelopers/android_vendor_jiayu_s3_h560"  revision="cm-13.0"/>
  <project path="kernel/jiayu/h560"      name="MediatekAndroidDevelopers/android_kernel_jiayu_s3_h560"  revision="android-6.0"/>

`

then a repo sync?

**Comment by lolipero** [comment]
When I update the repo, I update, but I dont start compile because I dont know the code of the phone for start compile. Do you know the code?

**Comment by alexzapatka** [comment]
Isn't it right in the title?  h560 for the s3, n560a for the s3+, though
you would be syncing different repos for that one.

I just don't know my repo lines are enough.  I also added one for twrp,
though I don't have all the source yet.  The tarball of the cm13 repo plus
s3, plus kernel, plus twrp is 19.9 GB, sitting on my vps.  My internet
connection is 6mbit ADSL.  About 27-32 hours to download it.

On Aug 14, 2016 4:45 PM, "Sergio" <notifications@github.com> wrote:

When I update the repo, I update, but I dont start compile because I dont
know the code of the phone for start compile. Do you know the code?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MediatekAndroidDevelopers/android_device_jiayu_s3_h560/issues/1#issuecomment-239695733>,
or mute the thread

**Comment by lolipero** [comment]
When write in ssh "breakfast h560" he says didnt exits this repo

**Comment by alexzapatka** [comment]
What are you putting in your manifest?

**Comment by lolipero** [comment]
I wrote the manifest for the Jiayu S3


  <project path="device/jiayu/h560"      name="MediatekAndroidDevelopers/android_device_jiayu_s3_h560"  revision="cm-13.0"/>
  <project path="vendor/jiayu/h560"      name="MediatekAndroidDevelopers/android_vendor_jiayu_s3_h560"  revision="cm-13.0"/>
  <project path="kernel/jiayu/h560"      name="MediatekAndroidDevelopers/android_kernel_jiayu_s3_h560"  revision="android-6.0"/>

**Comment by alexzapatka** [comment]
Yes, but what did you put in it?  What does it look like?  Are you putting
the device tree files in the right spot (device/jiayu/h560)?, the vendor
files?  And so you have a pre built kernel?  Superdragonpt said the build
is setup to run with a premade kernel.  I haven't gotten there with what
needs to be configured there in the config files.

**Comment by lolipero** [comment]
I put in device/jiayu/h560, but what is the premade kernel?

**Comment by dragonpt** [comment]
You don't need any manifest to build...
Just repo sync desire rom source using these repos on proper places
